modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0-or-later"

[[mods]]
modId="dragonloot"
version="${version}"
displayName="DragonLoot"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dragonloot"
authors="Pois1x, Globox_Z"
description='''Adds loot for the Ender Dragon.'''

[[dependencies.dragonloot]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="NONE"
side="BOTH"

[[dependencies.dragonloot]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="dragonloot.mixins.json"
