modLoader="javafml"
loaderVersion="[40,)"
license="GPL-3.0-or-later"

[[mods]]
modId="dragonloot"
version="${version}"
displayName="DragonLoot"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dragonloot"
authors="Pois1x, Globox_Z"
description='''Adds loot for the Ender Dragon.'''

[[dependencies.dragonloot]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.dragonloot]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="dragonloot.mixins.json"
